name: Branch Protection Validation
on:
  pull_request:
    branches: [main, staging]

jobs:
  validate-merge-policy:
    name: Validate Merge Policy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate Main Branch Merges
        if: github.base_ref == 'main'
        uses: KinsonDigital/BranchValidator@v1.0.0-preview.4
        with:
          branch-name: "${{ github.head_ref }}"
          validation-logic: "equalTo('staging')"
          fail-when-not-valid: true

      - name: Validate Staging Branch Merges
        if: github.base_ref == 'staging'
        uses: KinsonDigital/BranchValidator@v1.0.0-preview.4
        with:
          branch-name: "${{ github.head_ref }}"
          validation-logic: "equalTo('develop')"
          fail-when-not-valid: true