name: Branch Protection
on:
  push:
  create:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          if [ "${{ github.event_name }}" == "create" ]; then
            branch_name="${{ github.event.ref }}"
          else
            branch_name="${{ github.ref_name }}"
          fi
          
          if [[ ! $branch_name =~ ^(develop|staging|main|[0-9]+-(feature|bugfix)-.+)$ ]]; then
            echo "❌ Invalid branch name: $branch_name"
            # ブランチを削除する
            git push origin --delete $branch_name || true
            exit 1
          fi